name = "SPECTrecon"
uuid = "ab1be465-a7f0-4423-9048-0ee774b70ed9"
authors = ["Zongyu Li and Jeff Fessler and group"]
version = "0.3"

[deps]
AbstractFFTs = "621f4979-c628-5d54-868e-fcf4e3e8185c"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
ImageFiltering = "6a3955dd-da59-5b1f-98d4-e7296123deb5"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearInterpolators = "2fc109c4-9d77-11e9-32ff-e5c650334c16"
LinearMapsAA = "599c1a8e-b958-11e9-0d14-b1e6b2ecea07"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"

[compat]
AbstractFFTs = "1"
FFTW = "1"
ImageFiltering = "0.6, 0.7"
LinearInterpolators = "0.1"
LinearMapsAA = "0.12"
OffsetArrays = "1"
julia = "1.11"
