[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
MIRTjim = "170b2178-6dee-4cb0-8729-b3e8b57834cc"
SPECTrecon = "ab1be465-a7f0-4423-9048-0ee774b70ed9"

[compat]
Documenter = "0.27.7"
Literate = "2.9.3"
MIRTjim = "0.13"
