[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
LinearMapsAA = "7a12625a-238d-50fd-b39a-03d52299707e"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
MIRTjim = "170b2178-6dee-4cb0-8729-b3e8b57834cc"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SPECTrecon = "ab1be465-a7f0-4423-9048-0ee774b70ed9"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
UnitfulRecipes = "42071c24-d89e-48dd-8a24-8a12d9b8861f"

[compat]
Documenter = "0.27.7"
LinearMapsAA = "3.4"
Literate = "2.9.3"
MIRTjim = "0.13"
